import { mkdirSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { PERMISSION_REGISTRY } from '../common/constants/permissions.const';

type PermissionEntry = (typeof PERMISSION_REGISTRY)[keyof typeof PERMISSION_REGISTRY];

export function renderPermissionsFile(
  entries: Array<[string, PermissionEntry]>,
  groups: string[],
): string {
  const permissionObject = entries
    .map(([code, definition]) => `  ${code}: ${JSON.stringify(definition.key)},`)
    .join('\n');
  const definitionRows = entries
    .map(
      ([code, definition]) =>
        `  {
    code: ${JSON.stringify(code)},
    key: API_PERMISSIONS.${code},
    name: ${JSON.stringify(definition.name)},
    description: ${JSON.stringify(definition.description)},
    group: ${JSON.stringify(definition.group)},
  },`,
    )
    .join('\n');
  const defaultKeys = entries
    .map(([code]) => `  API_PERMISSIONS.${code},`)
    .join('\n');

  return `/* eslint-disable */
// This file is auto-generated by \`pnpm -C backend generate:permissions\`.
// Do not edit this file directly.

export const PERMISSION_GROUPS = ${JSON.stringify(groups)} as const;
export type PermissionGroup = (typeof PERMISSION_GROUPS)[number];

export const API_PERMISSIONS = {
${permissionObject}
} as const;

export type PermissionCode = keyof typeof API_PERMISSIONS;
export type PermissionKey = (typeof API_PERMISSIONS)[PermissionCode];

export interface PermissionDefinition {
  code: PermissionCode;
  key: PermissionKey;
  name: string;
  description: string;
  group: PermissionGroup;
}

export const PERMISSION_DEFINITIONS = [
${definitionRows}
] as const satisfies readonly PermissionDefinition[];

export const DEFAULT_PERMISSION_KEYS = [
${defaultKeys}
] as const satisfies readonly PermissionKey[];
`;
}

export function generatePermissionsFile() {
  const entries = Object.entries(PERMISSION_REGISTRY);
  const groups = [...new Set(entries.map(([, definition]) => definition.group))];
  const outputPath = resolve(
    process.cwd(),
    '../packages/shared-types/src/permissions.generated.ts',
  );

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, renderPermissionsFile(entries, groups), 'utf8');
  process.stdout.write(`generated ${outputPath}\n`);
}

if (require.main === module) {
  generatePermissionsFile();
}
