export type ApiErrorCode =
  | "INTERNAL_SERVER_ERROR"
  | "VALIDATION_FAILED"
  | "MISSING_BEARER_TOKEN"
  | "PERMISSION_DENIED"
  | "NOT_FOUND"
  | "MISSING_SESSION_USER"
  | "INVALID_ACCESS_TOKEN_TYPE"
  | "INVALID_OR_EXPIRED_ACCESS_TOKEN"
  | "INVALID_REFRESH_TOKEN_TYPE"
  | "INVALID_OR_EXPIRED_REFRESH_TOKEN"
  | "INVALID_AUDIENCE"
  | "LOGIN_RATE_LIMITED"
  | "INVALID_CREDENTIALS"
  | "ACCOUNT_NOT_ACTIVE"
  | "REFRESH_TOKEN_AUDIENCE_MISMATCH"
  | "REFRESH_TOKEN_INVALID_OR_REVOKED"
  | "REFRESH_TOKEN_EXPIRED"
  | "REFRESH_TOKEN_PAYLOAD_MISMATCH"
  | "ACCOUNT_NOT_FOUND"
  | "SESSION_EXPIRED"
  | "OLD_PASSWORD_INVALID"
  | "NEW_PASSWORD_MUST_DIFFER"
  | "ADMIN_PROFILE_NOT_FOUND"
  | "CUSTOMER_PROFILE_NOT_FOUND"
  | "CUSTOMER_BLOCKED"
  | "MISSING_ADMIN_SESSION_USER"
  | "MISSING_CUSTOMER_SESSION_USER"
  | "ADMIN_USER_NOT_FOUND"
  | "ROLE_NOT_FOUND"
  | "PERMISSION_NOT_FOUND"
  | "CUSTOMER_NOT_FOUND"
  | "CUSTOMER_PROFILE_NOT_CREATED"
  | "CUSTOMER_GROUP_NOT_FOUND"
  | "CUSTOMER_TAG_NOT_FOUND"
  | "CLIENT_RELEASE_FACTS_INVALID_TOKEN"
  | "CLIENT_RELEASE_FACTS_UNSUPPORTED_SCHEMA"
  | "CLIENT_RELEASE_FACTS_EMPTY_PACKAGES"
  | "CLIENT_RELEASE_NOT_FOUND"
  | "CLIENT_RELEASE_PACKAGE_NOT_FOUND"
  | "CLIENT_RELEASE_POLICY_NOT_FOUND"
  | "CLIENT_RELEASE_POLICY_INVALID_RECOMMENDATION"
  | "CLIENT_DOWNLOAD_UNAVAILABLE"
  | (string & {});

export interface ApiErrorPayload {
  statusCode: number;
  error:
    | string
    | string[]
    | ({ message?: string | string[]; code?: ApiErrorCode } & Record<
        string,
        unknown
      >);
  message: string | string[];
  code?: ApiErrorCode;
  timestamp: string;
  path: string;
  method?: string;
  locale?: string;
  details?: Record<string, unknown>;
}
