/* eslint-disable */
// This file is auto-generated by `pnpm -C apps/backend generate:permissions`.
// Do not edit this file directly.

export const PERMISSION_GROUPS = ["admin","dashboard","iam","customers","customer-groups","customer-tags","audit","customer-self"] as const;
export type PermissionGroup = (typeof PERMISSION_GROUPS)[number];

export const API_PERMISSIONS = {
  adminAccess: "admin:access",
  adminDashboardView: "admin:dashboard:view",
  adminUsersView: "admin:users:view",
  adminUsersCreate: "admin:users:create",
  adminUsersUpdate: "admin:users:update",
  adminUsersAssignRoles: "admin:users:assign-roles",
  adminRolesView: "admin:roles:view",
  adminRolesCreate: "admin:roles:create",
  adminRolesUpdate: "admin:roles:update",
  adminPermissionsView: "admin:permissions:view",
  adminCustomersView: "admin:customers:view",
  adminCustomersCreate: "admin:customers:create",
  adminCustomersUpdate: "admin:customers:update",
  adminCustomersSuspend: "admin:customers:suspend",
  adminCustomerGroupsView: "admin:customer-groups:view",
  adminCustomerGroupsManage: "admin:customer-groups:manage",
  adminCustomerTagsView: "admin:customer-tags:view",
  adminCustomerTagsManage: "admin:customer-tags:manage",
  adminAuditLogsView: "admin:audit-logs:view",
  customerSelfView: "customer:self:view",
  customerSelfUpdate: "customer:self:update",
} as const;

export type PermissionCode = keyof typeof API_PERMISSIONS;
export type PermissionKey = (typeof API_PERMISSIONS)[PermissionCode];

export interface PermissionDefinition {
  code: PermissionCode;
  key: PermissionKey;
  name: string;
  description: string;
  group: PermissionGroup;
}

export const PERMISSION_DEFINITIONS = [
  {
    code: "adminAccess",
    key: API_PERMISSIONS.adminAccess,
    name: "Admin Access",
    description: "Access the admin application shell.",
    group: "admin",
  },
  {
    code: "adminDashboardView",
    key: API_PERMISSIONS.adminDashboardView,
    name: "View Dashboard",
    description: "View the admin dashboard summary.",
    group: "dashboard",
  },
  {
    code: "adminUsersView",
    key: API_PERMISSIONS.adminUsersView,
    name: "View Users",
    description: "View admin user records.",
    group: "iam",
  },
  {
    code: "adminUsersCreate",
    key: API_PERMISSIONS.adminUsersCreate,
    name: "Create Users",
    description: "Create new admin users.",
    group: "iam",
  },
  {
    code: "adminUsersUpdate",
    key: API_PERMISSIONS.adminUsersUpdate,
    name: "Update Users",
    description: "Update admin users.",
    group: "iam",
  },
  {
    code: "adminUsersAssignRoles",
    key: API_PERMISSIONS.adminUsersAssignRoles,
    name: "Assign User Roles",
    description: "Assign roles to admin users.",
    group: "iam",
  },
  {
    code: "adminRolesView",
    key: API_PERMISSIONS.adminRolesView,
    name: "View Roles",
    description: "View role records.",
    group: "iam",
  },
  {
    code: "adminRolesCreate",
    key: API_PERMISSIONS.adminRolesCreate,
    name: "Create Roles",
    description: "Create new roles.",
    group: "iam",
  },
  {
    code: "adminRolesUpdate",
    key: API_PERMISSIONS.adminRolesUpdate,
    name: "Update Roles",
    description: "Update role definitions.",
    group: "iam",
  },
  {
    code: "adminPermissionsView",
    key: API_PERMISSIONS.adminPermissionsView,
    name: "View Permissions",
    description: "View the permission registry.",
    group: "iam",
  },
  {
    code: "adminCustomersView",
    key: API_PERMISSIONS.adminCustomersView,
    name: "View Customers",
    description: "View customer records.",
    group: "customers",
  },
  {
    code: "adminCustomersCreate",
    key: API_PERMISSIONS.adminCustomersCreate,
    name: "Create Customers",
    description: "Create customer records.",
    group: "customers",
  },
  {
    code: "adminCustomersUpdate",
    key: API_PERMISSIONS.adminCustomersUpdate,
    name: "Update Customers",
    description: "Update customer records.",
    group: "customers",
  },
  {
    code: "adminCustomersSuspend",
    key: API_PERMISSIONS.adminCustomersSuspend,
    name: "Suspend Customers",
    description: "Suspend customer access.",
    group: "customers",
  },
  {
    code: "adminCustomerGroupsView",
    key: API_PERMISSIONS.adminCustomerGroupsView,
    name: "View Customer Groups",
    description: "View customer groups.",
    group: "customer-groups",
  },
  {
    code: "adminCustomerGroupsManage",
    key: API_PERMISSIONS.adminCustomerGroupsManage,
    name: "Manage Customer Groups",
    description: "Create and update customer groups.",
    group: "customer-groups",
  },
  {
    code: "adminCustomerTagsView",
    key: API_PERMISSIONS.adminCustomerTagsView,
    name: "View Customer Tags",
    description: "View customer tags.",
    group: "customer-tags",
  },
  {
    code: "adminCustomerTagsManage",
    key: API_PERMISSIONS.adminCustomerTagsManage,
    name: "Manage Customer Tags",
    description: "Create and update customer tags.",
    group: "customer-tags",
  },
  {
    code: "adminAuditLogsView",
    key: API_PERMISSIONS.adminAuditLogsView,
    name: "View Audit Logs",
    description: "View audit log records.",
    group: "audit",
  },
  {
    code: "customerSelfView",
    key: API_PERMISSIONS.customerSelfView,
    name: "View Customer Profile",
    description: "View the current customer profile.",
    group: "customer-self",
  },
  {
    code: "customerSelfUpdate",
    key: API_PERMISSIONS.customerSelfUpdate,
    name: "Update Customer Profile",
    description: "Update the current customer profile.",
    group: "customer-self",
  },
] as const satisfies readonly PermissionDefinition[];

export const DEFAULT_PERMISSION_KEYS = [
  API_PERMISSIONS.adminAccess,
  API_PERMISSIONS.adminDashboardView,
  API_PERMISSIONS.adminUsersView,
  API_PERMISSIONS.adminUsersCreate,
  API_PERMISSIONS.adminUsersUpdate,
  API_PERMISSIONS.adminUsersAssignRoles,
  API_PERMISSIONS.adminRolesView,
  API_PERMISSIONS.adminRolesCreate,
  API_PERMISSIONS.adminRolesUpdate,
  API_PERMISSIONS.adminPermissionsView,
  API_PERMISSIONS.adminCustomersView,
  API_PERMISSIONS.adminCustomersCreate,
  API_PERMISSIONS.adminCustomersUpdate,
  API_PERMISSIONS.adminCustomersSuspend,
  API_PERMISSIONS.adminCustomerGroupsView,
  API_PERMISSIONS.adminCustomerGroupsManage,
  API_PERMISSIONS.adminCustomerTagsView,
  API_PERMISSIONS.adminCustomerTagsManage,
  API_PERMISSIONS.adminAuditLogsView,
  API_PERMISSIONS.customerSelfView,
  API_PERMISSIONS.customerSelfUpdate,
] as const satisfies readonly PermissionKey[];
