export {
  createAdminSdk,
  createApiClient,
  createCustomerSdk,
  type AdminApiSdk,
  type AdminSdkOptions,
  type ApiClient,
  type CustomerApiSdk,
} from "./client";
export type {
  AdminChangePasswordBody,
  AdminChangePasswordResult,
  AdminLoginBody,
  AdminLoginResult,
  AdminLogoutBody,
  AdminLogoutResult,
  AdminMeResult,
  AdminRefreshBody,
  AdminRefreshResult,
  AdminUserPathParams,
  AdminUsersBindRolesBody,
  AdminUsersBindRolesResult,
  AdminUsersCreateBody,
  AdminUsersCreateResult,
  AdminUsersGetResult,
  AdminUsersListQuery,
  AdminUsersListResult,
  AdminUsersUpdateBody,
  AdminUsersUpdateResult,
  AuditLogsListQuery,
  AuditLogsListResult,
  ClientDownloadsLatestQuery,
  ClientDownloadsLatestResult,
  ClientDownloadsListQuery,
  ClientDownloadsListResult,
  ClientUpdatesCheckQuery,
  ClientUpdatesCheckResult,
  ClientPackagesListQuery,
  ClientPackagesListResult,
  ClientReleasePathParams,
  ClientReleasePolicyPathParams,
  ClientReleasePolicyUpdateBody,
  ClientReleasePolicyUpdateResult,
  ClientReleasesGetResult,
  ClientReleasesListQuery,
  ClientReleasesListResult,
  CustomerChangePasswordBody,
  CustomerChangePasswordResult,
  CustomerGroupsCreateBody,
  CustomerGroupsCreateResult,
  CustomerGroupsListResult,
  CustomerGroupsUpdateBody,
  CustomerGroupsUpdateResult,
  CustomerGroupPathParams,
  CustomerLoginBody,
  CustomerLoginResult,
  CustomerLogoutBody,
  CustomerLogoutResult,
  CustomerMeResult,
  CustomerRefreshBody,
  CustomerRefreshResult,
  CustomerPathParams,
  CustomersCreateBody,
  CustomersCreateResult,
  CustomersGetResult,
  CustomersListQuery,
  CustomersListResult,
  CustomersResetPasswordBody,
  CustomersResetPasswordResult,
  CustomersUpdateBody,
  CustomersUpdateStatusBody,
  CustomersUpdateStatusResult,
  CustomersUpdateResult,
  CustomerTagPathParams,
  CustomerTagsCreateBody,
  CustomerTagsCreateResult,
  CustomerTagsListQuery,
  CustomerTagsListResult,
  CustomerTagsUpdateBody,
  CustomerTagsUpdateResult,
  DashboardStatsResult,
  PermissionsListResult,
  RolePathParams,
  RolesAssignPermissionsBody,
  RolesAssignPermissionsResult,
  RolesListQuery,
  RolesCreateBody,
  RolesCreateResult,
  RolesGetResult,
  RolesListResult,
  RolesUpdateBody,
  RolesUpdateResult,
} from "./openapi-contract";
export {
  createFetchTransport,
  createTaroTransport,
  type ApiRequestOptions,
  type ApiTransport,
  type FetchTransportOptions,
  type TaroRequestLike,
  type TaroRequestLikeOptions,
  type TaroRequestLikeResult,
  type TaroTransportOptions,
} from "./transport";
export type { paths as OpenApiPaths } from "./generated/openapi";
export {
  API_SDK_ENDPOINT_SURFACE,
  INTENTIONALLY_UNWRAPPED_OPENAPI_ENDPOINTS,
} from "./endpoints";
export type { ApiEndpointSurfaceEntry } from "./endpoints";
